### ISSUE TITLE
raw data input

### ISSUE THREAD

**Issue by jome1** [ClimateCompatibleGrowth/Geo-X-data-prep#1]
I am trying to use the GeoH2-data-prep tool. Some input data is missing or not clear which data where to put. 
Below you can find a table where I map the input data with the line of code in `spatial_data_prep.py`. For the "???" data input is not clear:

- Which file do I need to download from OSM? There are three different file formats: .osm.pbf | .shp.zip | .osm.bz2
In my case I would only download one country.
- Where to put the OSM file?
- Can you please add the protected classes dataset?
THX!

| data | link from github page   | name of downloaded file | line in code of `spatial_data_prep.py` |
| ------------- |:-------------:|:-----:|:-----:|
| The global oceans and seas geopackage can be downloaded from: | https://www.marineregions.org/downloads.php | GOaS_v1_20211214_gpkg | oceanPath = os.path.join(data_path, "GOaS_v1_20211214_gpkg", "goas_v01.gpkg") |
| The country boundaries shapefile can be downloaded from:| https://www.naturalearthdata.com/downloads/50m-cultural-vectors/50m-admin-0-countries-2/ | ne_50m_admin_0_countries | regionPath = os.path.join(data_path, 'ne_50m_admin_0_countries', 'ne_50m_admin_0_countries.shp') |
| OpenStreetMap layers can be downloaded from: | https://download.geofabrik.de/africa.html | ??? | ??? |
| The Corine Land Cover dataset can be downloaded from: | https://zenodo.org/records/3939050 |PROBAV_LC100_global_v3.0.1_2019-nrt_Discrete-Classification-map_EPSG-4326.tif| clcRasterPath = os.path.join(data_path, "PROBAV_LC100_global_v3.0.1_2019-nrt_Discrete-Classification-map_EPSG-4326.tif")|
| The protected classes dataset can be downloaded from: | ??? | ??? | protectedAreaPath = os.path.join(data_path, 'Africa_protect_class_1.geojson') |

**Comment by alycialeonard** [comment]
Thanks for asking about this! Changes to address these questions have been pushed to main. Answers below:

- Which file do I need to download from OSM? There are three different file formats: .osm.pbf | .shp.zip | .osm.bz2 - _You need to download and extract the Shapefiles (.shp.zip). This is now indicated in the ReadMe._
- In my case I would only download one country. _That's fine! Just add one country name to the country list in the files as indicated n the ReadMe._
- Where to put the OSM file? _Please extract them into a folder called 'OSM/[CountryName]' under 'Raw_Spatial_Data'. This is now indicated in the ReadMe._
- Can you please add the protected classes dataset? _This was generated using OpenStreetMap files for a specific research case. To keep things simpler for off-the-shelf use, we have removed this dataset for now. Please do feel free to add additional Corine Land Cover classes to workflow.py in order to protect additional types of area._

**Comment by alycialeonard** [comment]
Just for clarity as well, you can now see the usage of the OSM data more clearly (i.e., in OSM_path in spatial_data_prep.py)
